name: CNEggRoulette
main: me.derflash.plugins.eggroulette.CNEggRoulette
version: '${project.version}'
url: http://www.cube-nation.de/

authors: [ DerFlash, BangL ]
depend: [ Vault ]

commands:
  egg:
    description: Manage eggroulette
    aliases: [er, roulette]
